---
- name: config elk vm with docker
  hosts : elk 
  become: true
  tasks:
   - name: set vm.max_map_count to 262144 in sysctl
     sysctl: name={{ item.key }} value={{ item.value }}
     with_items:
     - { key: "vm.max_map_count", value: "262144" }

   - name : docker.io
     apt: 
      update_cache: yes
      name: docker.io
      state: present
      
   - name : Install pip3
     apt:
      force_apt_get: yes
      name: python3-pip
      state: present
   - name : Install python docker module
     pip:
      name: docker
      state : present
   - name: download and launch a docker elk container
     docker_container:
       name: elk
       image: sebp/elk:761
       state: started
       restart_policy: always
       # Please list the ports that ELK runs on
       published_ports:
          -  5601:5601
          -  9200:9200
          -  5044:5044

   - name: Make sure docker service is started
     systemd:
     name: docker 
     enabled: yes
      

